[2019-08-17 16:12:53,867] - [test_04_div.py:47] - [INFO] - [------测试结束------]
[2019-08-17 16:12:53,868] - [test_10_send_mes_request_case.py:24] - [INFO] - [------TestStart------]
[2019-08-17 16:12:55,615] - [test_10_send_mes_request_case.py:43] - [INFO] - [测试用例为：正确手机号码发送信息 执行结果是: Pass]
[2019-08-17 16:12:56,832] - [test_10_send_mes_request_case.py:43] - [INFO] - [测试用例为：格式错误的手机号码发送信息 执行结果是: Pass]
[2019-08-17 16:12:57,082] - [test_10_send_mes_request_case.py:43] - [INFO] - [测试用例为：短信模板不为1 执行结果是: Pass]
[2019-08-17 16:12:57,264] - [test_10_send_mes_request_case.py:43] - [INFO] - [测试用例为：ip为空 执行结果是: Pass]
[2019-08-17 16:12:57,497] - [test_10_send_mes_request_case.py:43] - [INFO] - [测试用例为：模板为空 执行结果是: Pass]
[2019-08-17 16:12:57,740] - [test_10_send_mes_request_case.py:43] - [INFO] - [测试用例为：手机号码为空 执行结果是: Pass]
[2019-08-17 16:12:57,852] - [test_10_send_mes_request_case.py:53] - [INFO] - [-------TestEnd-------]
[2019-08-17 16:12:57,975] - [test_11_user_register_request_case.py:26] - [INFO] - [------测试开始------]
[2019-08-17 16:12:58,342] - [test_11_user_register_request_case.py:64] - [INFO] - [成功发送短信验证码的测试用例 的执行结果为: Pass]
[2019-08-17 16:13:00,232] - [test_11_user_register_request_case.py:64] - [INFO] - [手机号错误的测试用例 的执行结果为: Pass]
[2019-08-17 16:13:00,438] - [test_11_user_register_request_case.py:64] - [INFO] - [注册名称为空的测试用例 的执行结果为: Pass]
[2019-08-17 16:13:00,643] - [test_11_user_register_request_case.py:64] - [INFO] - [渠道信息不正确的测试用例 的执行结果为: Pass]
[2019-08-17 16:13:00,897] - [test_11_user_register_request_case.py:64] - [INFO] - [密码为空的测试用例 的执行结果为: Pass]
[2019-08-17 16:13:01,141] - [test_11_user_register_request_case.py:64] - [INFO] - [IP为空的测试用例 的执行结果为: Pass]
[2019-08-17 16:13:01,654] - [test_11_user_register_request_case.py:64] - [INFO] - [成功注册的测试用例 的执行结果为: Pass]
[2019-08-17 16:13:01,872] - [test_11_user_register_request_case.py:64] - [INFO] - [重复注册的测试用例 的执行结果为: Pass]
[2019-08-17 16:13:01,987] - [test_11_user_register_request_case.py:76] - [INFO] - [------测试结束------]
[2019-08-17 16:13:02,112] - [test_12_user_auth_request_case.py:26] - [INFO] - [------测试开始------]
[2019-08-17 16:13:02,429] - [test_12_user_auth_request_case.py:64] - [INFO] - [成功发送验证码的测试用例 的执行结果为: Pass]
[2019-08-17 16:13:02,642] - [test_12_user_auth_request_case.py:69] - [ERROR] - [成功注册的测试用例 的执行结果为: Fail, 失败的原因是: {'retCode': 20042003, 'retInfo': 该用户已存在}]
[2019-08-17 16:13:02,910] - [test_12_user_auth_request_case.py:69] - [ERROR] - [uid为空的测试用例 的执行结果为: Fail, 失败的原因是: Unmarshalling Error: For input string: "" ]
[2019-08-17 16:13:03,077] - [test_12_user_auth_request_case.py:76] - [INFO] - [------测试结束------]
[2019-08-19 21:29:05,203] - [test_01_add.py:20] - [INFO] - [------测试开始------]
[2019-08-19 21:29:05,204] - [test_01_add.py:37] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-08-19 21:29:05,311] - [test_01_add.py:37] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-08-19 21:29:05,413] - [test_01_add.py:37] - [INFO] - [测试零与零相加 的执行结果为: Pass]
[2019-08-19 21:29:05,511] - [test_01_add.py:37] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-08-19 21:29:05,615] - [test_01_add.py:37] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-08-19 21:29:05,725] - [test_01_add.py:48] - [INFO] - [------测试结束------]
[2019-08-19 21:29:05,725] - [test_02_sub.py:20] - [INFO] - [------测试开始------]
[2019-08-19 21:29:05,725] - [test_02_sub.py:37] - [INFO] - [测试负数与负数相减 的执行结果为: Pass]
[2019-08-19 21:29:05,821] - [test_02_sub.py:37] - [INFO] - [测试负数与正数相减 的执行结果为: Pass]
[2019-08-19 21:29:05,921] - [test_02_sub.py:37] - [INFO] - [测试零与零相减 的执行结果为: Pass]
[2019-08-19 21:29:06,039] - [test_02_sub.py:37] - [INFO] - [测试正数与正数相减 的执行结果为: Pass]
[2019-08-19 21:29:06,132] - [test_02_sub.py:37] - [INFO] - [测试正数与负数相减 的执行结果为: Pass]
[2019-08-19 21:29:06,230] - [test_02_sub.py:47] - [INFO] - [------测试结束------]
[2019-08-19 21:29:06,230] - [test_03_minus.py:20] - [INFO] - [------测试开始------]
[2019-08-19 21:29:06,230] - [test_03_minus.py:37] - [INFO] - [测试负数与负数相乘 的执行结果为: Pass]
[2019-08-19 21:29:06,338] - [test_03_minus.py:37] - [INFO] - [测试负数与正数相乘 的执行结果为: Pass]
[2019-08-19 21:29:06,451] - [test_03_minus.py:37] - [INFO] - [测试零与零相乘 的执行结果为: Pass]
[2019-08-19 21:29:06,546] - [test_03_minus.py:37] - [INFO] - [测试正数与正数相乘 的执行结果为: Pass]
[2019-08-19 21:29:06,652] - [test_03_minus.py:37] - [INFO] - [测试正数与负数相乘 的执行结果为: Pass]
[2019-08-19 21:29:06,744] - [test_03_minus.py:47] - [INFO] - [------测试结束------]
[2019-08-19 21:29:06,744] - [test_04_div.py:20] - [INFO] - [------测试开始------]
[2019-08-19 21:29:06,744] - [test_04_div.py:37] - [INFO] - [测试负数与负数相除 的执行结果为: Pass]
[2019-08-19 21:29:06,849] - [test_04_div.py:37] - [INFO] - [测试负数与正数相除 的执行结果为: Pass]
[2019-08-19 21:29:06,942] - [test_04_div.py:41] - [ERROR] - [测试零与零相除 的执行结果为: Fail]
[2019-08-19 21:29:07,036] - [test_04_div.py:37] - [INFO] - [测试正数与正数相除 的执行结果为: Pass]
[2019-08-19 21:29:07,145] - [test_04_div.py:37] - [INFO] - [测试正数与负数相除 的执行结果为: Pass]
[2019-08-19 21:29:07,239] - [test_04_div.py:47] - [INFO] - [------测试结束------]
[2019-08-19 21:29:07,240] - [test_10_send_mes_request_case.py:24] - [INFO] - [------TestStart------]
[2019-08-19 21:29:07,577] - [test_10_send_mes_request_case.py:43] - [INFO] - [测试用例为：正确手机号码发送信息 执行结果是: Pass]
[2019-08-19 21:29:07,770] - [test_10_send_mes_request_case.py:43] - [INFO] - [测试用例为：格式错误的手机号码发送信息 执行结果是: Pass]
[2019-08-19 21:29:07,960] - [test_10_send_mes_request_case.py:43] - [INFO] - [测试用例为：短信模板不为1 执行结果是: Pass]
[2019-08-19 21:29:08,176] - [test_10_send_mes_request_case.py:43] - [INFO] - [测试用例为：ip为空 执行结果是: Pass]
[2019-08-19 21:29:08,387] - [test_10_send_mes_request_case.py:43] - [INFO] - [测试用例为：模板为空 执行结果是: Pass]
[2019-08-19 21:29:08,557] - [test_10_send_mes_request_case.py:43] - [INFO] - [测试用例为：手机号码为空 执行结果是: Pass]
[2019-08-19 21:29:08,674] - [test_10_send_mes_request_case.py:53] - [INFO] - [-------TestEnd-------]
[2019-08-19 21:29:08,814] - [test_11_user_register_request_case.py:26] - [INFO] - [------测试开始------]
[2019-08-19 21:29:09,080] - [test_11_user_register_request_case.py:64] - [INFO] - [成功发送短信验证码的测试用例 的执行结果为: Pass]
[2019-08-19 21:29:09,550] - [test_11_user_register_request_case.py:64] - [INFO] - [手机号错误的测试用例 的执行结果为: Pass]
[2019-08-19 21:29:09,762] - [test_11_user_register_request_case.py:64] - [INFO] - [注册名称为空的测试用例 的执行结果为: Pass]
[2019-08-19 21:29:09,967] - [test_11_user_register_request_case.py:64] - [INFO] - [渠道信息不正确的测试用例 的执行结果为: Pass]
[2019-08-19 21:29:10,180] - [test_11_user_register_request_case.py:64] - [INFO] - [密码为空的测试用例 的执行结果为: Pass]
[2019-08-19 21:29:10,436] - [test_11_user_register_request_case.py:64] - [INFO] - [IP为空的测试用例 的执行结果为: Pass]
[2019-08-19 21:29:11,113] - [test_11_user_register_request_case.py:64] - [INFO] - [成功注册的测试用例 的执行结果为: Pass]
[2019-08-19 21:29:11,339] - [test_11_user_register_request_case.py:64] - [INFO] - [重复注册的测试用例 的执行结果为: Pass]
[2019-08-19 21:29:11,447] - [test_11_user_register_request_case.py:76] - [INFO] - [------测试结束------]
[2019-08-19 21:29:11,585] - [test_12_user_auth_request_case.py:26] - [INFO] - [------测试开始------]
[2019-08-19 21:29:11,863] - [test_12_user_auth_request_case.py:64] - [INFO] - [成功发送验证码的测试用例 的执行结果为: Pass]
[2019-08-19 21:29:12,081] - [test_12_user_auth_request_case.py:69] - [ERROR] - [成功注册的测试用例 的执行结果为: Fail, 失败的原因是: {'retCode': 20042003, 'retInfo': 该用户已存在}]
[2019-08-19 21:29:12,278] - [test_12_user_auth_request_case.py:69] - [ERROR] - [uid为空的测试用例 的执行结果为: Fail, 失败的原因是: Unmarshalling Error: For input string: "" ]
[2019-08-19 21:29:12,421] - [test_12_user_auth_request_case.py:76] - [INFO] - [------测试结束------]
[2019-08-19 23:06:42,952] - [http_request_class.py:32] - [ERROR] - [DELETE is not define]
[2019-08-19 23:07:27,789] - [http_request_class.py:32] - [ERROR] - [DELETE is not define]
[2019-08-19 23:08:02,042] - [http_request_class.py:32] - [ERROR] - [DELETE is not define]
[2019-08-19 23:08:24,220] - [http_request_class.py:32] - [ERROR] - [DELETE is not define]
[2019-08-19 23:08:50,516] - [http_request_class.py:32] - [ERROR] - [DELETE is not define]
[2019-08-19 23:09:08,341] - [http_request_class.py:32] - [ERROR] - [method DELETE is not define]
[2019-08-20 19:22:00,742] - [http_request_class.py:32] - [ERROR] - [method DELETE is not define]
[2019-08-20 19:22:24,571] - [http_request_class.py:32] - [ERROR] - [Method DELETE is not define]
[2019-08-20 23:11:55,930] - [http_request_class.py:32] - [ERROR] - [Method DELETE is not define]
[2019-08-20 23:12:09,387] - [http_request_class.py:32] - [ERROR] - [Method DELETE is not define]
[2019-09-04 10:48:17,100] - [http_request_class.py:37] - [ERROR] - [Method DELETE is not define]
[2019-09-04 14:22:05,009] - [test_01_add.py:26] - [INFO] - [------测试开始------]
[2019-09-04 14:22:05,009] - [test_01_add.py:43] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-09-04 14:22:05,224] - [test_01_add.py:43] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-09-04 14:22:05,367] - [test_01_add.py:43] - [INFO] - [测试零与零相加 的执行结果为: Pass]
[2019-09-04 14:22:05,509] - [test_01_add.py:43] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-09-04 14:22:05,652] - [test_01_add.py:43] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-09-04 14:22:05,794] - [test_01_add.py:54] - [INFO] - [------测试结束------]
[2019-09-04 14:22:05,794] - [test_02_sub.py:26] - [INFO] - [------测试开始------]
[2019-09-04 14:22:05,794] - [test_02_sub.py:43] - [INFO] - [测试负数与负数相减 的执行结果为: Pass]
[2019-09-04 14:22:05,936] - [test_02_sub.py:43] - [INFO] - [测试负数与正数相减 的执行结果为: Pass]
[2019-09-04 14:22:06,083] - [test_02_sub.py:43] - [INFO] - [测试零与零相减 的执行结果为: Pass]
[2019-09-04 14:22:06,226] - [test_02_sub.py:43] - [INFO] - [测试正数与正数相减 的执行结果为: Pass]
[2019-09-04 14:22:06,370] - [test_02_sub.py:43] - [INFO] - [测试正数与负数相减 的执行结果为: Pass]
[2019-09-04 14:22:06,511] - [test_02_sub.py:53] - [INFO] - [------测试结束------]
[2019-09-04 14:22:06,511] - [test_03_minus.py:26] - [INFO] - [------测试开始------]
[2019-09-04 14:22:06,513] - [test_03_minus.py:43] - [INFO] - [测试负数与负数相乘 的执行结果为: Pass]
[2019-09-04 14:22:06,687] - [test_03_minus.py:43] - [INFO] - [测试负数与正数相乘 的执行结果为: Pass]
[2019-09-04 14:22:06,828] - [test_03_minus.py:43] - [INFO] - [测试零与零相乘 的执行结果为: Pass]
[2019-09-04 14:22:06,972] - [test_03_minus.py:43] - [INFO] - [测试正数与正数相乘 的执行结果为: Pass]
[2019-09-04 14:22:07,113] - [test_03_minus.py:43] - [INFO] - [测试正数与负数相乘 的执行结果为: Pass]
[2019-09-04 14:22:07,257] - [test_03_minus.py:53] - [INFO] - [------测试结束------]
[2019-09-04 14:22:07,258] - [test_04_div.py:26] - [INFO] - [------测试开始------]
[2019-09-04 14:22:07,258] - [test_04_div.py:43] - [INFO] - [测试负数与负数相除 的执行结果为: Pass]
[2019-09-04 14:22:07,401] - [test_04_div.py:43] - [INFO] - [测试负数与正数相除 的执行结果为: Pass]
[2019-09-04 14:22:07,547] - [test_04_div.py:47] - [ERROR] - [测试零与零相除 的执行结果为: Fail]
[2019-09-04 14:22:07,694] - [test_04_div.py:43] - [INFO] - [测试正数与正数相除 的执行结果为: Pass]
[2019-09-04 14:22:07,838] - [test_04_div.py:43] - [INFO] - [测试正数与负数相除 的执行结果为: Pass]
[2019-09-04 14:22:07,980] - [test_04_div.py:53] - [INFO] - [------测试结束------]
[2019-09-04 14:22:07,981] - [test_10_send_mes_request_case.py:29] - [INFO] - [------TestStart------]
[2019-09-04 14:22:07,985] - [test_10_send_mes_request_case.py:58] - [INFO] - [-------TestEnd-------]
[2019-09-04 14:22:08,097] - [test_11_user_register_request_case.py:32] - [INFO] - [------测试开始------]
[2019-09-04 14:22:08,127] - [test_11_user_register_request_case.py:82] - [INFO] - [------测试结束------]
[2019-09-04 14:22:08,234] - [test_12_user_auth_request_case.py:32] - [INFO] - [------测试开始------]
[2019-09-04 14:22:08,239] - [test_12_user_auth_request_case.py:82] - [INFO] - [------测试结束------]
