[2019-11-01 13:56:33,936] - [test_01_add.py:29] - [INFO] - [------测试开始------]
[2019-11-01 13:56:33,939] - [test_01_add.py:47] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 13:56:33,939] - [test_01_add.py:47] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 13:56:33,940] - [test_01_add.py:52] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 13:56:33,940] - [test_01_add.py:47] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 13:56:33,943] - [test_01_add.py:47] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 13:56:34,224] - [test_01_add.py:63] - [INFO] - [------测试结束------]
[2019-11-01 13:58:50,397] - [test_01_add.py:29] - [INFO] - [------测试开始------]
[2019-11-01 13:58:50,400] - [test_01_add.py:47] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 13:58:50,402] - [test_01_add.py:47] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 13:58:50,402] - [test_01_add.py:52] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 13:58:50,403] - [test_01_add.py:47] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 13:58:50,418] - [test_01_add.py:47] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 13:58:50,730] - [test_01_add.py:63] - [INFO] - [------测试结束------]
[2019-11-01 14:05:43,660] - [test_01_add.py:29] - [INFO] - [------测试开始------]
[2019-11-01 14:05:43,663] - [test_01_add.py:47] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 14:05:43,663] - [test_01_add.py:47] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 14:05:43,664] - [test_01_add.py:52] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:05:43,664] - [test_01_add.py:47] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 14:05:43,666] - [test_01_add.py:47] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:05:44,059] - [test_01_add.py:63] - [INFO] - [------测试结束------]
[2019-11-01 14:06:59,138] - [test_01_add.py:29] - [INFO] - [------测试开始------]
[2019-11-01 14:06:59,141] - [test_01_add.py:50] - [ERROR] - [测试负数与负数相加 的执行结果为: Fail]
[2019-11-01 14:06:59,141] - [test_01_add.py:50] - [ERROR] - [测试负数与正数相加 的执行结果为: Fail]
[2019-11-01 14:06:59,142] - [test_01_add.py:50] - [ERROR] - [测试正数与正数相加 的执行结果为: Fail]
[2019-11-01 14:06:59,145] - [test_01_add.py:50] - [ERROR] - [测试正数与负数相加 的执行结果为: Fail]
[2019-11-01 14:06:59,419] - [test_01_add.py:71] - [INFO] - [------测试结束------]
[2019-11-01 14:09:22,347] - [test_01_add.py:29] - [INFO] - [------测试开始------]
[2019-11-01 14:09:22,350] - [test_01_add.py:55] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 14:09:22,351] - [test_01_add.py:55] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 14:09:22,355] - [test_01_add.py:60] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:09:22,355] - [test_01_add.py:55] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 14:09:22,371] - [test_01_add.py:55] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:09:22,643] - [test_01_add.py:71] - [INFO] - [------测试结束------]
[2019-11-01 14:12:52,591] - [test_01_add.py:29] - [INFO] - [------测试开始------]
[2019-11-01 14:12:52,593] - [test_01_add.py:55] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 14:12:52,594] - [test_01_add.py:55] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 14:12:52,595] - [test_01_add.py:60] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:12:52,596] - [test_01_add.py:55] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 14:12:52,597] - [test_01_add.py:55] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:12:52,879] - [test_01_add.py:71] - [INFO] - [------测试结束------]
[2019-11-01 14:16:17,428] - [test_01_add.py:29] - [INFO] - [------测试开始------]
[2019-11-01 14:16:17,430] - [test_01_add.py:55] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 14:16:17,430] - [test_01_add.py:55] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 14:16:17,432] - [test_01_add.py:60] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:16:17,434] - [test_01_add.py:55] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 14:16:17,436] - [test_01_add.py:55] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:16:17,655] - [test_01_add.py:71] - [INFO] - [------测试结束------]
[2019-11-01 14:16:24,253] - [test_01_add.py:29] - [INFO] - [------测试开始------]
[2019-11-01 14:16:24,256] - [test_01_add.py:55] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 14:16:24,259] - [test_01_add.py:55] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 14:16:24,259] - [test_01_add.py:60] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:16:24,260] - [test_01_add.py:55] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 14:16:24,267] - [test_01_add.py:55] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:16:24,487] - [test_01_add.py:71] - [INFO] - [------测试结束------]
[2019-11-01 14:16:36,400] - [test_01_add.py:29] - [INFO] - [------测试开始------]
[2019-11-01 14:16:36,403] - [test_01_add.py:55] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 14:16:36,405] - [test_01_add.py:55] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 14:16:36,406] - [test_01_add.py:60] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:16:36,407] - [test_01_add.py:55] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 14:16:36,408] - [test_01_add.py:55] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:16:36,609] - [test_01_add.py:71] - [INFO] - [------测试结束------]
[2019-11-01 14:16:39,857] - [test_01_add.py:29] - [INFO] - [------测试开始------]
[2019-11-01 14:16:39,860] - [test_01_add.py:55] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 14:16:39,860] - [test_01_add.py:55] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 14:16:39,861] - [test_01_add.py:60] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:16:39,861] - [test_01_add.py:55] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 14:16:39,864] - [test_01_add.py:55] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:16:40,095] - [test_01_add.py:71] - [INFO] - [------测试结束------]
[2019-11-01 14:16:53,776] - [test_01_add.py:29] - [INFO] - [------测试开始------]
[2019-11-01 14:16:53,779] - [test_01_add.py:55] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 14:16:53,781] - [test_01_add.py:55] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 14:16:53,782] - [test_01_add.py:60] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:16:53,783] - [test_01_add.py:55] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 14:16:53,799] - [test_01_add.py:55] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:16:54,011] - [test_01_add.py:71] - [INFO] - [------测试结束------]
[2019-11-01 14:16:56,985] - [test_01_add.py:29] - [INFO] - [------测试开始------]
[2019-11-01 14:16:56,988] - [test_01_add.py:55] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 14:16:56,988] - [test_01_add.py:55] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 14:16:56,989] - [test_01_add.py:60] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:16:56,989] - [test_01_add.py:55] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 14:16:56,990] - [test_01_add.py:55] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:16:57,233] - [test_01_add.py:71] - [INFO] - [------测试结束------]
[2019-11-01 14:23:47,761] - [test_01_add.py:56] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 14:23:47,762] - [test_01_add.py:56] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 14:23:47,762] - [test_01_add.py:62] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:23:47,764] - [test_01_add.py:56] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 14:23:47,765] - [test_01_add.py:56] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:24:10,291] - [test_01_add.py:56] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 14:24:10,291] - [test_01_add.py:56] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 14:24:10,293] - [test_01_add.py:62] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:24:10,293] - [test_01_add.py:56] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 14:24:10,294] - [test_01_add.py:56] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:24:30,257] - [test_01_add.py:56] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 14:24:30,257] - [test_01_add.py:56] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 14:24:30,258] - [test_01_add.py:62] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:24:30,258] - [test_01_add.py:56] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 14:24:30,258] - [test_01_add.py:56] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:25:30,116] - [test_01_add.py:56] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 14:25:30,116] - [test_01_add.py:56] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 14:25:30,119] - [test_01_add.py:62] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:25:30,120] - [test_01_add.py:56] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 14:25:30,132] - [test_01_add.py:56] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:25:56,381] - [test_01_add.py:56] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 14:25:56,382] - [test_01_add.py:56] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 14:25:56,384] - [test_01_add.py:56] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 14:25:56,383] - [test_01_add.py:62] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:25:56,385] - [test_01_add.py:56] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:26:21,244] - [test_01_add.py:56] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 14:26:21,244] - [test_01_add.py:56] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 14:26:21,245] - [test_01_add.py:62] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:26:21,245] - [test_01_add.py:56] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 14:26:21,249] - [test_01_add.py:56] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:26:41,008] - [test_01_add.py:56] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 14:26:41,008] - [test_01_add.py:56] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 14:26:41,009] - [test_01_add.py:62] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:26:41,009] - [test_01_add.py:56] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 14:26:41,010] - [test_01_add.py:56] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:27:40,130] - [test_01_add.py:62] - [ERROR] - [测试负数与负数相加 的执行结果为: Fail]
[2019-11-01 14:27:40,132] - [test_01_add.py:62] - [ERROR] - [测试负数与正数相加 的执行结果为: Fail]
[2019-11-01 14:27:40,132] - [test_01_add.py:62] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:27:40,132] - [test_01_add.py:62] - [ERROR] - [测试正数与正数相加 的执行结果为: Fail]
[2019-11-01 14:27:40,133] - [test_01_add.py:56] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:28:02,260] - [test_01_add.py:62] - [ERROR] - [测试负数与负数相加 的执行结果为: Fail]
[2019-11-01 14:28:02,261] - [test_01_add.py:62] - [ERROR] - [测试负数与正数相加 的执行结果为: Fail]
[2019-11-01 14:28:02,261] - [test_01_add.py:62] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:28:02,263] - [test_01_add.py:62] - [ERROR] - [测试正数与正数相加 的执行结果为: Fail]
[2019-11-01 14:28:02,267] - [test_01_add.py:62] - [ERROR] - [测试正数与负数相加 的执行结果为: Fail]
[2019-11-01 14:29:42,485] - [test_01_add.py:63] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 14:29:42,486] - [test_01_add.py:63] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 14:29:42,487] - [test_01_add.py:63] - [INFO] - [测试零与零相加 的执行结果为: Pass]
[2019-11-01 14:29:42,490] - [test_01_add.py:63] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 14:29:42,491] - [test_01_add.py:63] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:30:30,035] - [test_01_add.py:63] - [INFO] - [测试负数与负数相加 的执行结果为: Pass]
[2019-11-01 14:30:30,035] - [test_01_add.py:63] - [INFO] - [测试负数与正数相加 的执行结果为: Pass]
[2019-11-01 14:30:30,036] - [test_01_add.py:63] - [INFO] - [测试零与零相加 的执行结果为: Pass]
[2019-11-01 14:30:30,036] - [test_01_add.py:63] - [INFO] - [测试正数与正数相加 的执行结果为: Pass]
[2019-11-01 14:30:30,037] - [test_01_add.py:63] - [INFO] - [测试正数与负数相加 的执行结果为: Pass]
[2019-11-01 14:33:05,507] - [test_01_add.py:29] - [INFO] - [------测试开始------]
[2019-11-01 14:33:05,511] - [test_01_add.py:52] - [ERROR] - [测试负数与负数相加 的执行结果为: Fail]
[2019-11-01 14:33:05,511] - [test_01_add.py:52] - [ERROR] - [测试负数与正数相加 的执行结果为: Fail]
[2019-11-01 14:33:05,512] - [test_01_add.py:52] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:33:05,512] - [test_01_add.py:52] - [ERROR] - [测试正数与正数相加 的执行结果为: Fail]
[2019-11-01 14:33:05,513] - [test_01_add.py:52] - [ERROR] - [测试正数与负数相加 的执行结果为: Fail]
[2019-11-01 14:33:05,934] - [test_01_add.py:74] - [INFO] - [------测试结束------]
[2019-11-01 14:34:04,009] - [test_01_add.py:29] - [INFO] - [------测试开始------]
[2019-11-01 14:34:04,012] - [test_01_add.py:58] - [INFO] - [------测试结束------]
[2019-11-01 14:34:32,418] - [test_01_add.py:29] - [INFO] - [------测试开始------]
[2019-11-01 14:34:32,421] - [test_01_add.py:51] - [ERROR] - [测试负数与负数相加 的执行结果为: Fail]
[2019-11-01 14:34:32,551] - [test_01_add.py:51] - [ERROR] - [测试负数与正数相加 的执行结果为: Fail]
[2019-11-01 14:34:32,672] - [test_01_add.py:51] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:34:32,811] - [test_01_add.py:51] - [ERROR] - [测试正数与正数相加 的执行结果为: Fail]
[2019-11-01 14:34:32,928] - [test_01_add.py:51] - [ERROR] - [测试正数与负数相加 的执行结果为: Fail]
[2019-11-01 14:34:33,047] - [test_01_add.py:57] - [INFO] - [------测试结束------]
[2019-11-01 14:34:49,126] - [test_01_add.py:29] - [INFO] - [------测试开始------]
[2019-11-01 14:34:49,128] - [test_01_add.py:51] - [ERROR] - [测试负数与负数相加 的执行结果为: Fail]
[2019-11-01 14:34:49,243] - [test_01_add.py:51] - [ERROR] - [测试负数与正数相加 的执行结果为: Fail]
[2019-11-01 14:34:49,353] - [test_01_add.py:51] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 14:34:49,475] - [test_01_add.py:51] - [ERROR] - [测试正数与正数相加 的执行结果为: Fail]
[2019-11-01 14:34:49,582] - [test_01_add.py:51] - [ERROR] - [测试正数与负数相加 的执行结果为: Fail]
[2019-11-01 14:34:49,688] - [test_01_add.py:57] - [INFO] - [------测试结束------]
[2019-11-01 17:37:35,256] - [test_add.py:36] - [ERROR] - [测试负数与负数相加 的执行结果为: Fail]
[2019-11-01 17:37:35,256] - [test_add.py:36] - [ERROR] - [测试负数与正数相加 的执行结果为: Fail]
[2019-11-01 17:37:35,257] - [test_add.py:36] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 17:37:35,257] - [test_add.py:36] - [ERROR] - [测试正数与正数相加 的执行结果为: Fail]
[2019-11-01 17:37:35,260] - [test_add.py:36] - [ERROR] - [测试正数与负数相加 的执行结果为: Fail]
[2019-11-01 17:38:03,086] - [test_add.py:36] - [ERROR] - [测试负数与负数相加 的执行结果为: Fail]
[2019-11-01 17:38:03,086] - [test_add.py:36] - [ERROR] - [测试负数与正数相加 的执行结果为: Fail]
[2019-11-01 17:38:03,087] - [test_add.py:36] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 17:38:03,087] - [test_add.py:36] - [ERROR] - [测试正数与正数相加 的执行结果为: Fail]
[2019-11-01 17:38:03,089] - [test_add.py:36] - [ERROR] - [测试正数与负数相加 的执行结果为: Fail]
[2019-11-01 17:54:06,540] - [test_add.py:37] - [ERROR] - [测试负数与负数相加 的执行结果为: Fail]
[2019-11-01 17:54:06,541] - [test_add.py:37] - [ERROR] - [测试负数与正数相加 的执行结果为: Fail]
[2019-11-01 17:54:06,541] - [test_add.py:37] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 17:54:06,541] - [test_add.py:37] - [ERROR] - [测试正数与正数相加 的执行结果为: Fail]
[2019-11-01 17:54:06,542] - [test_add.py:37] - [ERROR] - [测试正数与负数相加 的执行结果为: Fail]
[2019-11-01 17:54:29,223] - [test_add.py:37] - [ERROR] - [测试负数与负数相加 的执行结果为: Fail]
[2019-11-01 17:54:29,223] - [test_add.py:37] - [ERROR] - [测试负数与正数相加 的执行结果为: Fail]
[2019-11-01 17:54:29,224] - [test_add.py:37] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 17:54:29,224] - [test_add.py:37] - [ERROR] - [测试正数与正数相加 的执行结果为: Fail]
[2019-11-01 17:54:29,225] - [test_add.py:37] - [ERROR] - [测试正数与负数相加 的执行结果为: Fail]
[2019-11-01 17:56:08,165] - [test_add.py:37] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 17:56:26,663] - [test_add.py:37] - [ERROR] - [测试负数与负数相加 的执行结果为: Fail]
[2019-11-01 17:56:29,341] - [test_add.py:37] - [ERROR] - [测试正数与负数相加 的执行结果为: Fail]
[2019-11-01 17:56:30,392] - [test_add.py:37] - [ERROR] - [测试正数与正数相加 的执行结果为: Fail]
[2019-11-01 17:56:31,480] - [test_add.py:37] - [ERROR] - [测试负数与正数相加 的执行结果为: Fail]
[2019-11-01 17:58:16,334] - [test_add.py:37] - [ERROR] - [测试负数与负数相加 的执行结果为: Fail]
[2019-11-01 17:58:16,334] - [test_add.py:37] - [ERROR] - [测试负数与正数相加 的执行结果为: Fail]
[2019-11-01 17:58:16,335] - [test_add.py:37] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 17:58:16,335] - [test_add.py:37] - [ERROR] - [测试正数与正数相加 的执行结果为: Fail]
[2019-11-01 17:58:16,336] - [test_add.py:37] - [ERROR] - [测试正数与负数相加 的执行结果为: Fail]
[2019-11-01 17:58:32,666] - [test_add.py:37] - [ERROR] - [测试负数与负数相加 的执行结果为: Fail]
[2019-11-01 17:58:32,667] - [test_add.py:37] - [ERROR] - [测试负数与正数相加 的执行结果为: Fail]
[2019-11-01 17:58:32,668] - [test_add.py:37] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 17:58:32,668] - [test_add.py:37] - [ERROR] - [测试正数与正数相加 的执行结果为: Fail]
[2019-11-01 17:58:32,672] - [test_add.py:37] - [ERROR] - [测试正数与负数相加 的执行结果为: Fail]
[2019-11-01 17:59:21,065] - [test_add.py:37] - [ERROR] - [测试正数与正数相加 的执行结果为: Fail]
[2019-11-01 17:59:48,929] - [test_add.py:37] - [ERROR] - [测试零与零相加 的执行结果为: Fail]
[2019-11-01 17:59:48,932] - [test_add.py:37] - [ERROR] - [测试负数与负数相加 的执行结果为: Fail]
[2019-11-01 17:59:48,932] - [test_add.py:37] - [ERROR] - [测试正数与负数相加 的执行结果为: Fail]
[2019-11-01 17:59:48,946] - [test_add.py:37] - [ERROR] - [测试负数与正数相加 的执行结果为: Fail]
[2019-12-18 10:35:11,106] - [test_06_login_request_case.py:34] - [INFO] - [------测试开始------]
[2019-12-18 10:35:11,599] - [test_06_login_request_case.py:66] - [INFO] - [------测试结束------]
[2019-12-19 13:43:50,583] - [test_06_login_request_case.py:35] - [INFO] - [------测试开始------]
[2019-12-19 13:43:50,798] - [test_06_login_request_case.py:67] - [INFO] - [------测试结束------]
